spring.application.name=MediFlow


# =========================
# MySQL
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Flyway
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


jwt.secret=MediFlowClaveSecretaSuperLargaParaJWT2026HackathonLatam
jwt.expiration=86400000

PYTHON_URL=${PYTHON_URL}

spring.ai.google.genai.api-key=${GEMINI_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.8-flash

management.endpoints.web.exposure.include=mappings